### ISSUE TITLE
Replay file name length

### ISSUE THREAD

**Issue by Californ1a** [speecil/LocalLeaderboard-PC#7]
The replay files have massively long filenames. Someone will likely run into Windows' max path limit (256 characters for the entire path+filename) with filenames that long if they're using something like BSManager to have multiple BS instances installed and the path to one of their instances is buried in a few subdirectories, or if they're using a different location for their Steam library folder.

The default Steam path is 88 characters (`C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\UserData\LocalLeaderboard\Replays\`), and adding one of the replay filenames brings it up to around 220 depending on the map name, mode, etc.

If any of the replay files make it exceed the max path limit, people might have trouble using windows explorer to move their userdata to a different instance, or to make a backup, or delete them if they remove the mod; they'd have to use a completely separate file explorer program that supports long paths (for whatever reason, windows explorer doesn't).

**Comment by speecil** [comment]
Hi there!

I was unaware of this, and I will condense the file name to just the song name + diff + timestamp which should keep it down
