### ISSUE TITLE
1.34.2 compatibility 

### ISSUE THREAD

**Issue by an0Nym0us63** [speecil/LocalLeaderboard-PC#8]
Hello, i was really searching a mod like this one.
Having more details on localleaderboard IS really cool.

Is it possible to make this mod working on 1.34.2 ?
Please

It doesnt seem to be working on my side.

**Comment by speecil** [comment]
Hi there!

To be honest, I have just been quite lazy to update to 1.34.x+

But a big update is underway that will definitely make it to the latest version of beat saber, stay tuned for announcements.

**Comment by an0Nym0us63** [comment]
Greeeeeeattttt. I would really be happy.

My main usage of beat saber is competing with my friends , family AT home.
And i would really enjoy having more stats on localleaderboard like % and so on. This would really increase the enjoyement and to spot where we Can maybe try to beat my wife or a Friend.

Thanks for the positive answer.
And really waiting for that

👍👍👍

**Comment by an0Nym0us63** [comment]
Is this mod showing more stats for party leader board such as accuracy /rank and so on ?

If not would it be easy to implement ?

**Comment by speecil** [comment]
The new stats include:

Average Accuracy for each hand
The highest amount of 115's hit in a row
The time dependency for each hand
The accuracy if no notes were missed
The amount of pauses during playtime



Currently, the party mode leaderboard is not supported, and LocalLeaderboard can only be accessed through the solo mode menu for the time being

**Comment by TheBlackParrot** [comment]
Any update on a version specifically for 1.34.2? I noticed it appeared for 1.36 on BeatMods, but it needs BSIPA 4.3.3, which isn't available for 1.34.2.

**Comment by speecil** [comment]
Unfortunately I will not be bringing it to 1.34.2 as its not the latest currently, and I am unsure as to whether I will have to make changes if I want to backport it.

**Comment by speecil** [comment]
Decided to backport it to 1.34.2, nearly done. Ill write another comment once ive finished testing

**Comment by speecil** [comment]
its done, will be uploading to beatmods soon
